version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - rajzik
  versioning-strategy: increase
  commit-message:
    prefix: deps
    prefix-development: build
